on:
  push:
    branches:
      - main

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: install lftp
        run: sudo apt install lftp
      - name: test the lftp (please work)
        run: lftp ${{ secrets.FTP_HOST }} <<< "user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; set ssl:verify_certificate false; ls"
