on:
  push:
    branches:
      - release

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: install lftp
        run: sudo apt install lftp
      - name: check current directory
        run: ls
      - name: test the lftp (please work)
        run: > 
          lftp ${{ secrets.FTP_HOST }} <<< "user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; \
                                             set ssl:verify_certificate false; \
                                             cd blucreativefest; \
                                             mput -e *.php; \
                                             mput -e admin/*.php -O admin/; \
                                             mput -e config/*.php -O config/; \
                                             ls"
